name: DrCCTProf

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ opened, synchronize, reopened ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install DrCCTProf
      run: |
        git clone --recurse git@github.com:Xuhpclab/DrCCTProf.git
        ./build.sh
        export drrun=~/DrCCTProf/build/bin64/drrun
    - name: Run proj0
      run: | 
        cd proj0
        gcc -g p0_test_app.c -o p0_test_app
