name: DrCCTProf

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Schedule to run at 00:00 UTC on the 1st of every month
    - cron: '0 0 1 * *'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACTION_PAT }}
        submodules: recursive
    - name: Install DrCCTProf
      run: |
        ./DrCCTProf/build.sh
        export drrun=~/DrCCTProf/build/bin64/drrun
    - name: Run proj0
      run: | 
        cd proj0
        gcc -g p0_test_app.c -o p0_test_app
        cd ../DrCCTProf/
        ./build.sh
        cd ../proj0
        ./run.sh
