name: DrCCTProf

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup env
      run: source setup-env.sh
    - name: Install DrCCTProf
      run: git clone --recurse git@github.com:Xuhpclab/DrCCTProf.git
    - name: Run proj0
      run: | 
        cd proj0
        gcc -g p0_test_app.c -o p0_test_app
