name: Project 3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Schedule to run at 00:00 UTC on the 1st of every month
    - cron: '0 0 1 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository with submodules
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive  # Clone submodules recursively

    # Install GCC 7.5
    - name: Install GCC 7.5
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-7 g++-7
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 100
        
    # Build the project
    - name: Build proj3
      run: |
        cd proj3
        ./build.sh
        ./run.sh 
