name: Project 2

on:
  pull_request:
    branches: [ main, opened, synchronize, reopened ]
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTION_PAT }}
        submodules: recursive
    - name: Run proj2
      run: |
        cd proj2
        

    - name: Run black
      run: |
        pip3 install black
        cd proj2
        black --check .
