name: Project 0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Schedule to run at 00:00 UTC on the 1st of every month
    - cron: '0 0 1 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository with submodules
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive  # Clone submodules recursively

    # Use an older compiler to avoid newer floating point compiler optimizaitons
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 9
        platform: x86

    # Build the project
    - name: Build proj0
      run: |
        cd proj0
        gcc -g -O0 -o p0_test_app p0_test_app.c
        cp -r drcctlib_instr_analysis ../DrCCTProf/src/clients
        bash run.sh
    continue-on-error: true
